### PR TITLE
WIP: Upgrading to silverstripe framework 4 alpha-7

### PR DESCRIPTION
**Pull request by stojg**
@chillu 
These are a bunch of things I hacked together to get SS4 alpha-7 sort of working on the demo site. There is still problems with running it nicely with over HTTPS, since there are some things that the env-shim cannot properly do. 

See this PR more as an inspiration for now.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Done now?

**Comment by stojg** [comment]
Yeah, it was a quick hack to get this migrated to a new stack. I'm not sure if anything of it at all was useful, mostly a learning experience for me.

**Comment by robbieaverill** [comment]
Cool - I think @chillu may have used this and it's merged into master now, will close

**Comment by robbieaverill** [comment]
Hold on, we're using this on the SSP stack... will leave it open for now. Ideally we could merge this into master?

**Comment by tractorcow** [comment]
Replaced with https://github.com/silverstripe/demo.silverstripe.org/pull/27

**Pull request closed without merging**
