### PR TITLE
Added usabilla button into the CMS for feedback collection

### PR DESCRIPTION
**Pull request by mandrew**
This code uses the existing usabilia feedback button used on the SilverStripe site but will be used to gather feedback regarding the CMS from the demo site

### CODE REVIEW

**Comment by chillu** [comment]
Can you confirm this doesn't overlap with any important CMS UI elements? For example, if its a button on the bottom right, does it overlay the CMS preview buttons? Can you add a screenshot please?

**Comment by dhensby** [comment]
@chillu debatable?!

**Comment by dhensby** [comment]
It could go bottom left below the left menu?

Small screens:



smaller than that it starts going over the WYSIWYG buttons.

**Comment by mandrew** [comment]
@chillu @dhensby I've briefly tested and can't see any huge issues. Usabilia won't let you create your own button or position it where you like, so were are pretty limited to positioning and this seemed to be the best option without annoying users at the bottom of the screen.
dashboard_-_usabilla

**Comment by dhensby** [comment]
I'm happy but just realised I don't have merge access

someone?!

**Comment by mandrew** [comment]
cheers @tractorcow, will do a push live now

**Comment by chillu** [comment]
Yup, looking good

**Pull request merged**
